openapi: 3.0.0
info:
  version: 1.0.0
  title: PayHub Brasil
tags:
  - name: Transaction
    description: Public Resources
paths:
  /v1/public/transaction:
    post:
      tags:
        - Transaction
      summary: Create new transaction and Payment
      operationId: postTransaction
      requestBody:
        $ref: "#/components/requestBodies/postTransaction"
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /v1/public/transaction/{id}:
    get:
      tags:
        - Transaction
      summary: Get transaction by ID
      operationId: getTransaction
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
servers:
  - url: https://api.payhubbrasil.com
components:
  requestBodies:
    postTransaction:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/postTransaction"
      description: Transaction object
      required: true
  schemas:
    postTransaction:
      type: object
      properties:
        client:
          type: object
          properties:
            name:
              empty: false
              type: string
              required: true
            email:
              type: string
              required: true
              empty: false
            client_type:
              required: true
              type: string
              allowed:
                - pf
                - pj
            cpf_cnpj_number:
              type: string
              required: true
              regex: ^(\d{3}\.\d{3}\.\d{3}\-\d{2}|\d{2}\.\d{3}\.\d{3}\/\d{4}\-\d{2})$
            company_name:
              type: string
              empty: false
              nullable: true
            trading_name:
              type: string
              nullable: true
            address_cep:
              required: true
              type: string
              regex: ^\d{5}-\d{3}$
            address_street:
              required: true
              type: string
              empty: false
            address_number:
              required: true
              type: string
              empty: false
            address_complement:
              type: string
            address_neighborhood:
              required: true
              type: string
              empty: false
            address_city:
              required: true
              type: string
              empty: false
            address_state:
              required: true
              type: string
              empty: false
              maxlength: 2
        transaction:
          type: object
          properties:
            description:
              type: string
            payment_method:
              type: string
              allowed:
                - boleto
                - card
              required: true
            gross_amount:
              type: number
              required: true
            due_date:
              type: integer
              required: true
            send_email:
              type: boolean
              required: true
        payment:
          type: object
          properties:
            card_holder:
              type: string
            card_number:
              type: string
            expiration_date:
              type: string
            security_code:
              type: string
            transaction_type:
              type: string
              allowed:
                - credit
                - debit